sonar.projectKey=0x524A_metricsd
sonar.projectName=metricsd
sonar.organization=0x524a

sonar.host.url=https://sonarcloud.io

sonar.sources=cmd,internal
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/vendor/**,**/*_test.go,docs/**,plugins/**,packaging/**

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
